#see https://darthpedro.net/2024/10/17/github-action-to-publish-to-nuget-org/
name: Publish NuGet Package
 
on:
  push:
    branches:
      - main
 
jobs:
  publish:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Specify the .NET version you need
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build the project
      run: dotnet build --configuration Release --no-restore
 
    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg
 
    - name: Publish NuGet package
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
